### ISSUE TITLE
pretrain model load error

### ISSUE THREAD

**Issue by ssbilakeri** [mangye16/ReID-Survey#14]
Hi, please helpme to resolve this error.

Traceback (most recent call last):
  File "tools/main.py", line 110, in <module>
    main()
  File "tools/main.py", line 57, in main
    model = build_model(cfg, num_classes)
  File ".\modeling\__init__.py", line 7, in build_model
    cfg.MODEL.GENERALIZED_MEAN_POOL, cfg.MODEL.PRETRAIN_CHOICE)
  File ".\modeling\baseline.py", line 126, in __init__
    self.base.load_param(model_path)
  File ".\modeling\backbones\resnet_nl.py", line 176, in load_param
    param_dict = torch.load(model_path)
  File "C:\Users\MAHE\anaconda3\envs\myenv\lib\site-packages\torch\serialization.py", line 365, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../resnet50-19c8e357.pth'

**Comment by mangye16** [comment]
This means that you did not have the pretrained ImageNet model "resnet50-19c8e357.pth". You may mannually download it at "https://download.pytorch.org/models/resnet50-19c8e357.pth" and put it in correct path.
