### ISSUE TITLE
模型训练跑过一轮后出现错误：ERROR:ignite.engine.engine.Engine:Engine run is terminating due to exception: 'int' object is not callable

### ISSUE THREAD

**Issue by JL0424** [mangye16/ReID-Survey#27]
具体的错误信息如下：
ERROR:ignite.engine.engine.Engine:Engine run is terminating due to exception: 'int' object is not callable
Traceback (most recent call last):
  File "./tools/main.py", line 117, in <module>
    main()
  File "./tools/main.py", line 105, in main
    do_train(cfg,
  File "/home/hk/student/jl/ReID-Survey-master/./tools/train.py", line 166, in do_train
    trainer.run(data_loader['train'], max_epochs=epochs)
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/engine/engine.py", line 889, in run
    return self._internal_run()
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/engine/engine.py", line 932, in _internal_run
    return next(self._internal_run_generator)
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/engine/engine.py", line 990, in _internal_run_as_gen
    self._handle_exception(e)
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/engine/engine.py", line 644, in _handle_exception
    raise e
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/engine/engine.py", line 962, in _internal_run_as_gen
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/engine/engine.py", line 431, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/handlers/checkpoint.py", line 1009, in __call__
    super(ModelCheckpoint, self).__call__(engine)
  File "/home/hk/anaconda3/envs/jl/lib/python3.8/site-packages/ignite/handlers/checkpoint.py", line 408, in __call__
    priority = self.score_function(engine)
TypeError: 'int' object is not callable
这是什么原因呢，请各位大佬帮忙看一下

**Comment by mango2steen** [comment]
我刚也出现这个错误，ignite换个版本试试

**Comment by JL0424** [comment]
> 我刚也出现这个错误，ignite换个版本试试

谢谢，实现了，确实是这个原因

**Comment by allstardust** [comment]
更换什么版本呢？

**Comment by JL0424** [comment]
> 更换什么版本呢？

这个版本你试一下：'0.1.2'，我安装的是这个版本，环境没动过应该没错
